### ISSUE TITLE
Values on the map

### ISSUE THREAD

**Issue by aomaesalu** [neuroactive/koroonakaart#3]
Having numerical values for each county on the map (in addition to the heatmapping) would simplify the overview of the spread of the virus. Ideally, the most important value(s) (e.g. the total number of cases and/or the number of active cases) would be always visible, and additional information could be displayed on mouseover.

**Comment by neuroactive** [comment]
We are planning to make the map interactive, so that detailed county-level information can be viewed, as well as municipality-level information if possible. As part of adding the interactivity, we may show values on hover. However, we have switched off the interactivity of the map temporarily as there were some bugs with that.

**Comment by neuroactive** [comment]
As the code for this app is now being maintained by Open Data Estonia, I have moved this issue to their repository:

https://github.com/okestonia/koroonakaart/issues/15
